### PR TITLE
Upgrade testing platforms

### PR DESCRIPTION
**Pull request by meteorcloudy**
Also testing presubmit after repo transfer

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@skeletonkey Can you take a look at the failing test? Also failing in postsubmit.

**Comment by skeletonkey** [comment]
I will take a look at this tomorrow.

**Comment by skeletonkey** [comment]
@meteorcloudy I took the following steps to get this build to pass:
- I've removed the complex_deps test. It uses IO::Tty, which has some unique challenges with the new Macs. I will create a test to replace it
- two of the newer tests do not run on the latest Mac platform. I will create issues and work with the original author to get those tests working again.

This branch should be ready to merge.

**Review by skeletonkey — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Thanks a lot!

**Pull request merged**
